Exception on /auth/register [POST]
Traceback (most recent call last):
  File "C:\Users\micah\Documents\WorkSpaces\Projects\advert-backend\env\Lib\site-packages\sqlalchemy\engine\base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\micah\Documents\WorkSpaces\Projects\advert-backend\env\Lib\site-packages\sqlalchemy\engine\default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.StringDataRightTruncation: value too long for type character varying(128)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\micah\Documents\WorkSpaces\Projects\advert-backend\env\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\micah\Documents\WorkSpaces\Projects\advert-backend\env\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\micah\Documents\WorkSpaces\Projects\advert-backend\env\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\micah\Documents\WorkSpaces\Projects\advert-backend\env\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\micah\Documents\WorkSpaces\Projects\advert-backend\app\jwt_auth\routes.py", line 22, in registerUser
    new_user.save()
  File "C:\Users\micah\Documents\WorkSpaces\Projects\advert-backend\app\models\userAuthModel.py", line 43, in save
    db.session.commit()
  File "C:\Users\micah\Documents\WorkSpaces\Projects\advert-backend\env\Lib\site-packages\sqlalchemy\orm\scoping.py", line 598, in commit
    return self._proxied.commit()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\micah\Documents\WorkSpaces\Projects\advert-backend\env\Lib\site-packages\sqlalchemy\orm\session.py", line 1969, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "C:\Users\micah\Documents\WorkSpaces\Projects\advert-backend\env\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\micah\Documents\WorkSpaces\Projects\advert-backend\env\Lib\site-packages\sqlalchemy\orm\session.py", line 1256, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "C:\Users\micah\Documents\WorkSpaces\Projects\advert-backend\env\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\micah\Documents\WorkSpaces\Projects\advert-backend\env\Lib\site-packages\sqlalchemy\orm\session.py", line 1231, in _prepare_impl
    self.session.flush()
  File "C:\Users\micah\Documents\WorkSpaces\Projects\advert-backend\env\Lib\site-packages\sqlalchemy\orm\session.py", line 4312, in flush
    self._flush(objects)
  File "C:\Users\micah\Documents\WorkSpaces\Projects\advert-backend\env\Lib\site-packages\sqlalchemy\orm\session.py", line 4447, in _flush
    with util.safe_reraise():
  File "C:\Users\micah\Documents\WorkSpaces\Projects\advert-backend\env\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\micah\Documents\WorkSpaces\Projects\advert-backend\env\Lib\site-packages\sqlalchemy\orm\session.py", line 4408, in _flush
    flush_context.execute()
  File "C:\Users\micah\Documents\WorkSpaces\Projects\advert-backend\env\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute
    rec.execute(self)
  File "C:\Users\micah\Documents\WorkSpaces\Projects\advert-backend\env\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "C:\Users\micah\Documents\WorkSpaces\Projects\advert-backend\env\Lib\site-packages\sqlalchemy\orm\persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "C:\Users\micah\Documents\WorkSpaces\Projects\advert-backend\env\Lib\site-packages\sqlalchemy\orm\persistence.py", line 1227, in _emit_insert_statements
    result = connection.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\micah\Documents\WorkSpaces\Projects\advert-backend\env\Lib\site-packages\sqlalchemy\engine\base.py", line 1416, in execute
    return meth(
           ^^^^^
  File "C:\Users\micah\Documents\WorkSpaces\Projects\advert-backend\env\Lib\site-packages\sqlalchemy\sql\elements.py", line 517, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\micah\Documents\WorkSpaces\Projects\advert-backend\env\Lib\site-packages\sqlalchemy\engine\base.py", line 1639, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\micah\Documents\WorkSpaces\Projects\advert-backend\env\Lib\site-packages\sqlalchemy\engine\base.py", line 1848, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\micah\Documents\WorkSpaces\Projects\advert-backend\env\Lib\site-packages\sqlalchemy\engine\base.py", line 1988, in _exec_single_context
    self._handle_dbapi_exception(
  File "C:\Users\micah\Documents\WorkSpaces\Projects\advert-backend\env\Lib\site-packages\sqlalchemy\engine\base.py", line 2344, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\micah\Documents\WorkSpaces\Projects\advert-backend\env\Lib\site-packages\sqlalchemy\engine\base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\micah\Documents\WorkSpaces\Projects\advert-backend\env\Lib\site-packages\sqlalchemy\engine\default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DataError: (psycopg2.errors.StringDataRightTruncation) value too long for type character varying(128)

[SQL: INSERT INTO users (id, username, email, password, role, created_at) VALUES (%(id)s, %(username)s, %(email)s, %(password)s, %(role)s, %(created_at)s)]
[parameters: {'id': '27b843ef', 'username': 'micahshallom', 'email': 'micahshallom@gmail.com', 'password': 'scrypt:32768:8:1$6AYN6ALanDqoPCIR$37b5c02d2ab4416c432fe6497c8d62a3b715dc69817c9e77599dad4b8b8650d87acee0167e046df2806450858d7a49a88337f6aa3961b52f3d68987193230b81', 'role': 'buyer', 'created_at': datetime.datetime(2024, 1, 30, 8, 13, 33, 123458)}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
